# Generated by Django 2.1 on 2018-08-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velostore', '0004_auto_20180806_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mark',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
